services:
  postgres:
    image: postgres:17
    container_name: mini_shop_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_shop_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mini_shop_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./mini_shop_backend_nest
      dockerfile: Dockerfile
    container_name: mini_shop_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env.docker
    ports:
      - "3000:3000"

volumes:
  postgres_data:
